title: blog.punk.voyage
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog following the journey and adventures of Martin and Erin aboard their
  52ft narrowboat 'Carla'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.punk.voyage" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: s3krit
github_username: s3krit

remote_theme: yous/whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme: jekyll-theme-tactile